# Generated by Django 5.0 on 2024-01-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='report',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
