# Generated by Django 5.0 on 2024-01-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_friendshiprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='http://127.0.0.1:8000/media/avatars/default-user-icon.png', null=True, upload_to='avatars'),
        ),
    ]
