# Generated by Django 5.0 on 2024-01-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default-user-icon.png', null=True, upload_to='avatars'),
        ),
    ]
