# Generated by Django 5.0 on 2024-01-15 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='post_id',
            new_name='post',
        ),
    ]
